site_name: mdEdit [en]
pages:
- Home: 'index.md'
- User Guide:
    - 'Installation': 'use/install.md'
    - 'Configuration': 'use/configuration.md'
    - 'Use': 'use/use.md'
- About:
    - 'License': 'about/license.md'
    - 'Release Notes': 'about/release-notes.md'
theme: mkdocs
